AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  URI:
    Type: String
    Description: The URI used to name resources [projectName-env-gitUsername]
  Cron:
    Type: String
    Description: The cron to trigger lambda
  Env:
    Type: String
    Default: dev
    Description: The environment variables for Lambda
    AllowedValues:
      - dev
      - production
      - staging
  Url:
    Type: String
    Description: Url for Data Elaboration Api
  AcmArn:
    Type: String
    Description: The ARN of the ssl certificate genereted on ACM
  HostedZoneId:
    Type: String
    Description: Hosted zone Id on route 53
  JwtSecret:
    Type: String
    Description: The secret to sign Json Web Token
  Project:
    Type: String
    Description: The name of the project
  Target:
    Type: String
    Description: The target application name
  SourceTable:
    Type: String
    Description: The name of the table where retrive data
  HotelTable:
    Type: String
    Description: The name of the administration table whit hotels data

Resources:
  DataElaborationCron:
    Type: AWS::Serverless::Application
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      Location: ../cron/template.yml
      Parameters:
        URI: !Ref URI
        Cron: !Ref Cron
        Env: !Ref Env
        Project: !Ref Project
        Target: !Ref Target
        SourceTable: !Ref SourceTable
        HotelTable: !Ref HotelTable

  DataElaborationApi:
    Type: AWS::Serverless::Application
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      Location: ../api/template.yml
      Parameters:
        URI: !Ref URI
        Env: !Ref Env
        Url: !Ref Url
        AcmArn: !Ref AcmArn
        HostedZoneId: !Ref HostedZoneId
        JwtSecret: !Ref JwtSecret
